name: coacd_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - gymnasium
  - rtree
  - pip
  - pip:
      - torch==2.7.1
      - stable-baselines3==2.6.0
      - trimesh==4.7.0
      - tensorboard
      - matplotlib
      - pandas
      - tqdm
      - tabulate
      - yacs
      - fvcore
      - iopath
      - coacd
      - pyrender
      - "git+https://github.com/facebookresearch/pytorch3d.git@stable"